<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>

    <PackageId>EcoLabirinto</PackageId>

    <TargetFramework>net9.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Formula.Engine" Version="1.2.8" />
  </ItemGroup>
</Project>